apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-game-deployment
  labels:
    app: mini-game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mini-game
  template:
    metadata:
      labels:
        app: mini-game
    spec:
      containers:
      - name: mini-game
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mini-game-service
  labels:
    name: mini-game
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
  selector:
    name: mini-game