/**
 * Welcome screen
 * 
 * Entry page of the game.
 */

import { Asset, Assets } from '~/assets/assets';
import { BaseScene } from '~/scenes/basescene';
import { SoundHelper } from '~/helpers/soundhelper';
import { GameMode } from '~/externalgameconfig';
import { PercentageBar } from '~/widgets/percentagebar';

export class Welcome extends BaseScene {

  private __loadCompleted = false;

  private __progressBar: PercentageBar;

  constructor() {
    super({
      key: 'Welcome'
    });

    this.__progressBar = new PercentageBar(this);
  }

  init(): void {
    this.attachDefaultHandlers();
  }

  preload(): void {
    if (!this.__loadCompleted) {
      this.__progressBar.create(
        this.cameras.main.centerX - 350, 
        this.cameras.main.centerY - 25, 
        700, 
        50);
  
      this.load.on('progress', this.onLoadProgress.bind(this));
      this.load.on('complete', this.onLoadCompleted.bind(this));

      Assets.getInstance().forEach(this.loadAsset.bind(this));
    }
  }

  create(): void {
    this.addButton('title', Assets.IMAGE_TITLE,
      function (this: Welcome) {
        this.sound.play(Assets.SOUND_BLOP, { loop: false });
        if (GameMode.server == this.getExternalGameConfig().gameMode) {
          this.transitionToServerConsole();
        } else {
          this.transitionToMenu();
        }
      }, this);

    this.addButton('btnFullscreen', Assets.IMAGE_BTN_FULLSCREEN,
      function (this: Welcome) {
        this.setFullscreenMode(true);
      }, this);

    this.addButton('btnWindowed', Assets.IMAGE_BTN_WINDOWED,
      function (this: Welcome) {
        this.setFullscreenMode(false);
      }, this);

    let dims = this.getScreenDimension();
    this.updateLayout(dims.width, dims.height);

    let music = this.sound.add(Assets.MUSIC_THEME);
    SoundHelper.playBackgroundMusic(music);

    this.sound.add(Assets.SOUND_BLOP);
  }

  updateLayout(width: number, height: number): void {
    let size = Math.min(width, height);
    let margin = size * 0.1;
    let btnsize = size * 0.08;

    let isFullscreen = this.scale.isFullscreen;

    (this.children.getByName('btnFullscreen') as Phaser.GameObjects.Sprite)
      .setPosition(width - margin, margin)
      .setDisplaySize(btnsize, btnsize)
      .setActive(!isFullscreen)
      .setVisible(!isFullscreen);

    (this.children.getByName('btnWindowed') as Phaser.GameObjects.Sprite)
      .setPosition(width - margin, margin)
      .setDisplaySize(btnsize, btnsize)
      .setActive(isFullscreen)
      .setVisible(isFullscreen);

    (this.children.getByName('title') as Phaser.GameObjects.Sprite)
      .setPosition(width / 2, height / 2)
      .setDisplaySize(size * 0.6, size * 0.75 * 0.6);
  }

  update(time: number, delta: number): void {
  }

  onResize(gameSize: Phaser.Structs.Size, baseSize: Phaser.Structs.Size, displaySize: Phaser.Structs.Size, resolution: number) {
    super.onResize(gameSize, baseSize, displaySize, resolution);
    this.updateLayout(displaySize.width, displaySize.height);
  }

  onShutdown() {
    this.detachDefaultHandlers();
  }

  setFullscreenMode(on: boolean) {
    this.sound.play(Assets.SOUND_BLOP, { loop: false });
    if (this.scale.isFullscreen == on) {
      return;
    }
    if (on) {
      this.scale.startFullscreen();
    } else {
      this.scale.stopFullscreen();
    }
  }

  transitionToMenu(): void {
    this.scene.start('Menu');
  }

  transitionToServerConsole(): void {
    this.scene.start('ServerConsole');
  }

  private onLoadProgress(value: number) {
    this.__progressBar.setValue(value);
  }

  private onLoadCompleted() {
    this.__loadCompleted = true;
    this.__progressBar.destroy();
  }

  private loadAsset(asset: Asset, key: string, map: Assets) {
    if (asset.kind == "image") {
      this.load.image(key, asset.url);
    } else if (asset.kind == "music") {
      this.load.audio(key, asset.url);
    } else if (asset.kind == "sound") {
      this.load.audio(key, asset.url);
    } else if (asset.kind == "spine") {
      // spine assets load the spritesheets implicitly, which is why
      // the loader needs to know the base location og the spritesheet
      this.load.setPath(asset.url);
      // and since the parcel bundler does not handle paths in atlas files, 
      // the bundled files cannot be used for loading atlas. this could
      // be fixed later via parcel plugin that provied apine support.
      // insted, for now, the file names generated by parcel are
      // reversed to the original names, so that they can be loaded
      // from the static folder instead. RRR
      let base = (asset.url2 ? asset.url2 : '').split('.').shift();
      let skeleton: string = base + '.skeleton';
      let atlas: string = base + '.atlas';

      // @ts-ignore
      this.load.spine(key, skeleton, atlas);
      //this.load.setPath(path);
    } else {
      throw new Error("Unhandled asset type " + asset.kind + " from " + asset.url);
    }
  }
}
