/**
 * Welcome screen
 * 
 * Entry page of the game.
 */

import { Asset, Assets } from '~/assets/assets';
import { BaseScene } from '~/scenes/basescene';

export class Welcome extends BaseScene {

  private __loadCompleted = false;

  constructor() {
    super({
      key: 'Welcome'
    });
  }

  init(): void {
    this.attachDefaultHandlers();
  }

  preload(): void {
    if (!this.__loadCompleted) {
      Assets.getInstance().forEach(this.loadAsset.bind(this));
    }
  }

  create(): void {
    this.addButton('title', Assets.IMAGE_TITLE,
      function (this: Welcome) {
          this.transitionToMenu();
      }, this);

    let dims = this.getScreenDimension();
    this.updateLayout(dims.width, dims.height);

    let spine = this.add.spine(200, 300, Assets.SPINE_BOY, "idle", true);
    spine.scale = 0.5;

    spine = this.add.spine(500, 700, Assets.SPINE_BOY, "run", true);
    spine.depth = 2;
    spine.drawDebug = true;
    spine.drawBones = true;
  }

  updateLayout(width: number, height: number): void {
    let size = Math.min(width, height);
    let margin = size * 0.1;
    let btnsize = size * 0.08;

    (this.children.getByName('title') as Phaser.GameObjects.Sprite)
      .setPosition(width / 2, height / 2)
      .setDisplaySize(size * 0.6, size * 0.75 * 0.6);
  }

  update(time: number, delta: number): void {
  }

  onResize(gameSize: Phaser.Structs.Size, baseSize: Phaser.Structs.Size, displaySize: Phaser.Structs.Size, resolution: number) {
    super.onResize(gameSize, baseSize, displaySize, resolution);
    this.updateLayout(displaySize.width, displaySize.height);
  }

  onShutdown() {
    this.detachDefaultHandlers();
  }

  transitionToMenu(): void {
    this.scene.start('Menu');
  }

  private loadAsset(asset: Asset, key: string, map: Assets) {
    if (asset.kind == "image") {
      this.load.image(key, asset.url);
    } else if (asset.kind == "spine") {
      // spine assets load the spritesheets implicitly, which is why
      // the loader needs to know the base location og the spritesheet
      this.load.setPath(asset.url);
      // and since the parcel bundler does not handle paths in atlas files, 
      // the bundled files cannot be used for loading atlas. this could
      // be fixed e.g. via parcel plugin that provides spine support.
      // insted, for now, the file names generated by parcel are
      // reversed to the original names, so that they can be loaded
      // from the static folder instead. RRR
      let base = (asset.url2 ? asset.url2 : '').split('.').shift();
      let skeleton: string = base + '.skeleton';
      let atlas: string = base + '.atlas';

      // @ts-ignore
      this.load.spine(key, skeleton, atlas, false);
      //this.load.setPath(path);
    } else {
      throw new Error("Unhandled asset type " + asset.kind + " from " + asset.url);
    }
  }
}
